# DO NOT CHANGE THIS FILE!
#
# This is run on a non-standard gitlab runner so any changes you make may break in unexpected ways.
# If you feel for some reason this file MUST be changed, please post on the course forum so it can
# be discussed between you and course staff.
#
image: cs2511docker/cs2511-gradle-8.8-ass2:e88cb7c

stages:
  - lint
  - tests
  - dryrun

lint:
  stage: lint
  needs: []
  only:
    - main
    - merge_requests
  script:
    - gradle lint
  allow_failure: false

test:
  stage: tests
  needs: []
  only:
    - main
    - merge_requests
  script:
    - gradle compile
    - echo "Running your tests"
    - gradle test
    - gradle coverage
    - echo "Successfully passed your own tests, now running dryrun build"
    - rm -rf app/src/test/
    - tar -xvf /data/assignment-ii-tests.tar -C app/src/
    - gradle compile

dryrun-sunstone-buildables:
  stage: dryrun
  needs: []
  only:
    - main
    - merge_requests
  when: manual
  allow_failure: true
  script:
    - echo "Running dryrun for sunstone and buildables"
    - rm -rf app/src/test/
    - tar -xvf /data/assignment-ii-tests.tar -C app/src/
    - gradle compile
    - echo "Checking if your code passes the dryrun test for sunstone and buildables"
    - gradle test --tests "dungeonmania.automarking.Dryrun.dryrunSunstoneAndBuildables"

dryrun-logic-switches:
  stage: dryrun
  needs: []
  only:
    - main
    - merge_requests
  when: manual
  allow_failure: true
  script:
    - echo "Running dryrun for logic switches"
    - rm -rf app/src/test/
    - tar -xvf /data/assignment-ii-tests.tar -C app/src/
    - gradle compile
    - echo "Checking if your code passes the dryrun test for logic switches"
    - gradle test --tests "dungeonmania.automarking.Dryrun.dryrunLogic"
